gatsby.settings:
  type: config_object
  label: 'Gatsby settings'
  mapping:
    server_url:
      type: uri
      label: 'Server URL'
    preview_callback_url:
      type: uri
      label: 'Preview callback URL'
    path_mapping:
      type: string
      label: 'Path Mapping'
    incrementalbuild_url:
      type: uri
      label: 'Incrmental build URL'
    build_published:
      type: boolean
      label: 'Build published'
    preview_entity_types:
      type: sequence
      label: 'Preview Entity Types'
      sequence:
        type: string

node.type.*.third_party.gatsby:
  type: mapping
  label: 'Gatsby node-type settings'
  mapping:
    preview:
      type: boolean
      label: 'Enable preview'
    target:
      type: string
      label: 'Preview target'
    iframe:
      type: boolean
      label: 'Enable iframe on node view'
