<?php

/**
 * @file
 * Contains lb_direct_add.module.
 */

use Drupal\lb_direct_add\LayoutBuilder;

/**
 * Implements hook_element_info_alter().
 *
 * This doesn't work because it is for changing broad-level
 * definitions for how elements are handled.It doesn't allow
 * for setting the configuration for an individual element.
 */
function lb_direct_add_element_info_alter(array &$types) {
  $types['layout_builder']['#pre_render'][] = LayoutBuilder::class . '::preRender';
}
