dependencies:
  config:
    - field.field.media.audio.field_transcribe_text
  module:
    - ezcontent_smart_article
content:
  field_transcribe_text:
    weight: 1
    label: above
    settings: {  }
    third_party_settings: {  }
    type: ez_smart_transcribe_view
    region: content
