dependencies:
  config:
    - field.field.media.audio.field_transcribe_text
  module:
    - ezcontent_smart_article
    - file
content:
  field_media_audio_file:
    type: file_generic
    weight: 0
    region: content
    settings:
      progress_indicator: throbber
    third_party_settings: {  }
  field_transcribe_text:
    type: ez_smart_transcribe_widget
    weight: 1
    region: content
    settings: {  }
    third_party_settings: {  }
