types:
  block_content: {  }
  comment: {  }
  contact_message: {  }
  content_moderation_state: {  }
  crop: {  }
  entity_embed_fake_entity: {  }
  file: {  }
  media: {  }
  node:
    '*': '*'
  paragraphs_library_item: {  }
  path_alias: {  }
  redirect: {  }
  shortcut: {  }
  taxonomy_term: {  }
  user: {  }
  paragraph: {  }
form_op_lock:
  block_content:
    mode: 0
    values: {  }
  comment:
    mode: 0
    values: {  }
  contact_message:
    mode: 0
    values: {  }
  content_moderation_state:
    mode: 0
    values: {  }
  crop:
    mode: 0
    values: {  }
  entity_embed_fake_entity:
    mode: 0
    values: {  }
  file:
    mode: 0
    values: {  }
  media:
    mode: 0
    values: {  }
  node:
    mode: 1
    values:
      edit: edit
  paragraphs_library_item:
    mode: 0
    values: {  }
  path_alias:
    mode: 0
    values: {  }
  redirect:
    mode: 0
    values: {  }
  shortcut:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
