settings:
  toolbar:
    rows:
      -
        -
          name: 'EZcontent Publish'
          items:
            - TextColor
            - BGColor
            - DrupalMediaLibrary
            - Preview
  plugins:
    stylescombo:
      styles: ''
    drupallink:
      linkit_enabled: true
      linkit_profile: default
    language:
      language_list: un
