dependencies:
  config:
    - field.storage.node.field_content
    - node.type.article
    - paragraphs.paragraphs_type.referenced_card
  module:
    - entity_reference_revisions
settings:
  handler: 'default:paragraph'
  handler_settings:
    negate: 1
    target_bundles:
      referenced_card: referenced_card
    target_bundles_drag_drop:
      referenced_card:
        enabled: true
        weight: -27
field_type: entity_reference_revisions
